@Web_HostAddress = https://localhost:7078

GET {{web_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{Web_HostAddress}}/api/contact/GetContactsSimple

###

GET {{Web_HostAddress}}/api/contact/GetContactsDetailed

###

POST {{Web_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "UserName":"test",
  "Password":"test"
}

###
# @name login
POST {{Web_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "UserName":"g",
  "Password":"g"
}

###

GET {{Web_HostAddress}}/api/auth
Accept: application/json
Authorization: Bearer {{login.response.body.$.token}}
###

@id=16
DELETE {{Web_HostAddress}}/api/contact/DeleteContact/{{id}}
Authorization: Bearer {{login.response.body.$.token}}

###

POST {{Web_HostAddress}}/api/contact/CreateContact
Content-Type: application/json

{
  //ContactCreateDTO
}

###

GET {{Web_HostAddress}}/api/contact/GetContact/{id:int}?id={{id}}

###
@id=9
PUT {{Web_HostAddress}}/api/contact/UpdateContact/{{id}}
Content-Type: application/json

{
  "FirstName":"Mike",
  "LastName":"Like",
  "Email":"spike@nike.com",
  "Password":"mikielikenike",
  "CategoryId ":"1",
  "SubCategory":"el-diablo",
  "PhoneNumber":"132567926",
  "DateOfBirth":"1/1/2000"
}

###
